export const apiPaths = {
  customers: "/api/v1/customers",
  customer: (id: string) => `/api/v1/customers/${id}`,
  customerBlock: (id: string) => `/api/v1/customers/${id}/block`,
  customerUnblock: (id: string) => `/api/v1/customers/${id}/unblock`,
  customerCreditCheck: (id: string) => `/api/v1/customers/${id}/credit-check`,
  customerStats: "/api/v1/customers/stats",
  invoices: "/api/v1/invoices",
  invoice: (id: string) => `/api/v1/invoices/${id}`,
  invoiceIssue: (id: string) => `/api/v1/invoices/${id}/issue`,
  invoiceOverdue: (id: string) => `/api/v1/invoices/${id}/overdue`,
  invoiceWriteOff: (id: string) => `/api/v1/invoices/${id}/writeoff`,
  invoicePayment: (id: string) => `/api/v1/invoices/${id}/payment`,
  invoiceDueDate: (id: string) => `/api/v1/invoices/${id}/due-date`,
  payments: "/api/v1/payments",
  paymentAllocateFifo: (id: string) => `/api/v1/payments/${id}/allocate/fifo`,
  paymentAllocateManual: (id: string) =>
    `/api/v1/payments/${id}/allocate/manual`,
  paymentAllocations: (id: string) => `/api/v1/payments/${id}/allocations`,
  invoiceAllocations: (invoiceId: string) =>
    `/api/v1/payments/invoices/${invoiceId}/allocations`,
  cheques: "/api/v1/cheques",
  cheque: (id: string) => `/api/v1/cheques/${id}`,
  chequeDeposit: (id: string) => `/api/v1/cheques/${id}/deposit`,
  chequeClear: (id: string) => `/api/v1/cheques/${id}/clear`,
  chequeBounce: (id: string) => `/api/v1/cheques/${id}/bounce`,
  aging: "/api/v1/aging",
  agingBuckets: "/api/v1/aging/buckets",
  agingDiscount: "/api/v1/aging/discount/calculate",
  creditNotes: "/api/v1/credit-notes",
  creditNote: (id: string) => `/api/v1/credit-notes/${id}`,
  creditNoteApply: (id: string) => `/api/v1/credit-notes/${id}/apply`,
  ledgerAccounts: "/api/v1/ledger/accounts",
  ledgerBalance: (account: string) => `/api/v1/ledger/balance/${account}`,
  ledgerTransaction: (id: string) => `/api/v1/ledger/transactions/${id}`,
  ledgerReference: (type: string, id: string) =>
    `/api/v1/ledger/reference/${type}/${id}`,
} as const;
